# Generated by Django 3.0.5 on 2020-05-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynoteapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteModel',
        ),
    ]
